# Generated by Django 5.0.2 on 2024-03-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_hotel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
