# Generated by Django 5.0.2 on 2024-03-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0004_alter_roomtype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='number_of_guest',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
