# Generated by Django 5.0.2 on 2024-03-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0005_room_check_in_date_room_check_out_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='province',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
