# Generated by Django 5.0.2 on 2024-03-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0006_city_hotel_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='fullname',
            field=models.CharField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
