# Generated by Django 5.0.2 on 2024-03-13 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0010_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingHistory',
        ),
    ]
