# Generated by Django 5.0.2 on 2024-03-13 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0013_room_image_roomtype_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='number_of_reviews',
        ),
    ]
