# Generated by Django 5.0.2 on 2024-03-19 03:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0015_amenity_remove_roomtype_amenities_roomtype_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_booking',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(upload_to='Hotel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(upload_to='Room'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='image',
            field=models.ImageField(upload_to='RoomType'),
        ),
    ]
