# Generated by Django 5.0.2 on 2024-03-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0016_booking_date_booking_alter_hotel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
