# Generated by Django 5.0.2 on 2024-04-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0019_remove_hotel_slug_booking_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='check_out_date',
        ),
    ]
