# Generated by Django 5.0.2 on 2024-04-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0019_booking_total_price_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='slug',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
