# Generated by Django 5.0.2 on 2024-03-18 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercustom',
            old_name='user_id',
            new_name='id',
        ),
    ]
