# Generated by Django 5.0.2 on 2024-03-21 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='role_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Auth.role'),
            preserve_default=False,
        ),
    ]
