# Generated by Django 5.0.2 on 2024-03-21 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_usercustom_role_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='role_id',
        ),
        
    ]
