# Generated by Django 5.0.2 on 2024-03-21 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_remove_usercustom_role_id_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='role_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Auth.role'),
            preserve_default=False,
        ),
        
    ]
